import "./globals.css";
import Header from "../../components/Header";
import Footer from "../../components/Footer";
import '@/app/style.css'

export const metadata = {
  title: "SuStylo",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased`}
      >
      <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}









